"""
Emotion API Router

REST API endpoints for AICO's emotion system.
Provides access to current emotional state and history.
"""

from typing import Annotated, Optional
from datetime import datetime, timedelta, UTC
from fastapi import APIRouter, HTTPException, Depends, Query
import os
from aico.core.logging import get_logger
from .schemas import EmotionStateResponse, EmotionHistoryResponse, EmotionHistoryItem
from .dependencies import get_current_user, get_emotion_engine
from backend.core.postgres_dependencies import get_uow
from aico.data.uow import UnitOfWork

logger = get_logger("aico.api.emotion.router")

router = APIRouter()


@router.get("/current", response_model=EmotionStateResponse)
async def get_current_emotion(
    user: Annotated[dict, Depends(get_current_user)],
    emotion_engine: Annotated[object, Depends(get_emotion_engine)]
):
    """
    Get AICO's current emotional state.
    
    **Authentication required:** Bearer token
    
    Returns the most recent emotional state generated by the emotion simulation engine,
    including primary emotion label, confidence, and dimensional values (valence, arousal, dominance).
    
    **Note:** Current implementation returns global emotional state. Future versions will support
    per-user emotional states for personalized interactions.
    """
    try:
        # Get current emotional state from engine
        current_state = emotion_engine.current_state
        
        if current_state is None:
            raise HTTPException(status_code=404, detail="No emotional state available")
        
        # Convert to response format
        return EmotionStateResponse(
            timestamp=current_state.timestamp.isoformat() + "Z",
            primary=current_state.subjective_feeling.value,
            confidence=current_state.intensity,
            valence=current_state.mood_valence,
            arousal=current_state.mood_arousal,
            dominance=0.5  # Default neutral dominance (not yet implemented in CPM)
        )
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error retrieving current emotion: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to retrieve emotional state: {str(e)}")


@router.get("/history", response_model=EmotionHistoryResponse)
async def get_emotion_history(
    user: Annotated[dict, Depends(get_current_user)],
    emotion_engine: Annotated[object, Depends(get_emotion_engine)],
    uow: Annotated[UnitOfWork, Depends(get_uow)],
    limit: int = Query(50, ge=1, le=1000, description="Maximum number of records to return"),
    hours: Optional[int] = Query(None, ge=1, description="Only return emotions from last N hours"),
    days: Optional[int] = Query(None, ge=1, description="Only return emotions from last N days"),
    since: Optional[str] = Query(None, description="ISO timestamp - only return emotions after this time"),
    feeling: Optional[str] = Query(None, description="Filter by specific emotion (e.g., 'calm', 'playful')")
):
    """
    Get AICO's emotional state history from database.
    
    **Authentication required:** Bearer token
    
    Returns a list of emotional states for mood arc visualization, queried directly from the database.
    States are ordered from most recent to oldest.
    
    **Smart filtering options:**
    - `limit`: Max records (1-1000, default: 50)
    - `hours`: Last N hours (e.g., hours=24 for last day)
    - `days`: Last N days (e.g., days=7 for last week)
    - `since`: ISO timestamp (e.g., 2025-11-20T00:00:00)
    - `feeling`: Filter by emotion (e.g., 'calm', 'playful', 'warm_concern')
    
    **Examples:**
    - `/history?limit=100` - Last 100 emotions
    - `/history?days=7` - All emotions from last 7 days
    - `/history?hours=24&feeling=calm` - All 'calm' emotions in last 24 hours
    - `/history?since=2025-11-20T00:00:00` - All emotions since Nov 20
    
    Args:
        user: Authenticated user (injected)
        emotion_engine: Emotion engine service (injected)
        limit: Maximum number of history entries to return
        hours: Filter to last N hours
        days: Filter to last N days
        since: Filter to emotions after this timestamp
        feeling: Filter by specific emotion label
    """
    try:
        # Build filters for repository query
        filters = {}
        
        # Time-based filters
        if since:
            try:
                # Validate ISO timestamp
                since_dt = datetime.fromisoformat(since.replace('Z', '+00:00'))
                filters["timestamp_gte"] = since_dt
            except ValueError:
                raise HTTPException(status_code=400, detail="Invalid 'since' timestamp format. Use ISO 8601 format.")
        elif hours:
            cutoff = datetime.now(UTC) - timedelta(hours=hours)
            filters["timestamp_gte"] = cutoff
        elif days:
            cutoff = datetime.now(UTC) - timedelta(days=days)
            filters["timestamp_gte"] = cutoff
        
        # Emotion filter
        if feeling:
            filters["feeling"] = feeling
        
        # Get emotion history from repository
        emotion_records = await uow.emotion_history.list(filters=filters, limit=limit)
        
        # Sort by timestamp DESC (most recent first)
        emotion_records.sort(key=lambda e: e.timestamp if e.timestamp else datetime.min, reverse=True)
        
        if not emotion_records:
            return EmotionHistoryResponse(count=0, history=[])
        
        # Convert to response format
        history_items = [
            EmotionHistoryItem(
                timestamp=record.timestamp.isoformat() if hasattr(record.timestamp, 'isoformat') else record.timestamp,
                feeling=record.feeling,
                valence=record.valence,
                arousal=record.arousal,
                intensity=record.intensity
            )
            for record in emotion_records
        ]

        # Emotion history ranges removed to reduce log noise
        
        return EmotionHistoryResponse(
            count=len(history_items),
            history=history_items
        )
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error retrieving emotion history: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to retrieve emotion history: {str(e)}")
