"""
Emotion API Router

REST API endpoints for AICO's emotion system.
Provides access to current emotional state and history.
"""

from typing import Annotated
from fastapi import APIRouter, HTTPException, Depends
from aico.core.logging import get_logger
from .schemas import EmotionStateResponse, EmotionHistoryResponse, EmotionHistoryItem
from .dependencies import get_current_user, get_emotion_engine

logger = get_logger("aico.api.emotion", "router")

router = APIRouter()


@router.get("/current", response_model=EmotionStateResponse)
async def get_current_emotion(
    user: Annotated[dict, Depends(get_current_user)],
    emotion_engine: Annotated[object, Depends(get_emotion_engine)]
):
    """
    Get AICO's current emotional state.
    
    **Authentication required:** Bearer token
    
    Returns the most recent emotional state generated by the emotion simulation engine,
    including primary emotion label, confidence, and dimensional values (valence, arousal, dominance).
    
    **Note:** Current implementation returns global emotional state. Future versions will support
    per-user emotional states for personalized interactions.
    """
    try:
        # Get current emotional state from engine
        current_state = emotion_engine.current_state
        
        if current_state is None:
            raise HTTPException(status_code=404, detail="No emotional state available")
        
        # Convert to response format
        return EmotionStateResponse(
            timestamp=current_state.timestamp.isoformat() + "Z",
            primary=current_state.subjective_feeling.value,
            confidence=current_state.intensity,
            valence=current_state.mood_valence,
            arousal=current_state.mood_arousal,
            dominance=0.5  # Default neutral dominance (not yet implemented in CPM)
        )
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error retrieving current emotion: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to retrieve emotional state: {str(e)}")


@router.get("/history", response_model=EmotionHistoryResponse)
async def get_emotion_history(
    user: Annotated[dict, Depends(get_current_user)],
    emotion_engine: Annotated[object, Depends(get_emotion_engine)],
    limit: int = 50
):
    """
    Get AICO's emotional state history.
    
    **Authentication required:** Bearer token
    
    Returns a list of recent emotional states for mood arc visualization.
    States are ordered from most recent to oldest.
    
    Args:
        user: Authenticated user (injected)
        emotion_engine: Emotion engine service (injected)
        limit: Maximum number of history entries to return (default: 50, max: 100)
    """
    try:
        # Validate limit
        if limit < 1:
            raise HTTPException(status_code=400, detail="Limit must be at least 1")
        if limit > 100:
            limit = 100
        
        # Get history from engine
        history = emotion_engine.state_history
        
        if not history:
            return EmotionHistoryResponse(count=0, history=[])
        
        # Convert to response format (most recent first)
        history_items = []
        for state in reversed(history[-limit:]):
            # Handle both compact dict format and flat format from DB
            if "label" in state:
                # Compact dict format from to_compact_dict()
                history_items.append(EmotionHistoryItem(
                    timestamp=state["timestamp"],
                    feeling=state["label"]["primary"],
                    valence=state["mood"]["valence"],
                    arousal=state["mood"]["arousal"],
                    intensity=state["label"]["intensity"]
                ))
            else:
                # Flat format from DB
                history_items.append(EmotionHistoryItem(
                    timestamp=state["timestamp"],
                    feeling=state["feeling"],
                    valence=state["valence"],
                    arousal=state["arousal"],
                    intensity=state["intensity"]
                ))
        
        return EmotionHistoryResponse(
            count=len(history_items),
            history=history_items
        )
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error retrieving emotion history: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to retrieve emotion history: {str(e)}")
