site_name: AICO - AI Companion Project
site_description: Building an emotionally present, interactive AI companion
site_author: Michael Böni
site_url: https://boeni-industries.github.io/aico

# Configuration
use_directory_urls: true

# Repository
repo_name: boeni-industries/aico
repo_url: https://github.com/boeni-industries/aico
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Boeni Industries AG

# Build directory (default: site)
# Note: GitHub Actions will handle deployment to gh-pages branch
# No need to change site_dir for GitHub Pages deployment

# Configuration
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    # Navigation behavior
    - navigation.instant    # Instant loading navigation
    - navigation.tracking   # URL is automatically updated with anchor
    - navigation.sections   # Render sections as groups
    - navigation.indexes    # Section index pages
    - navigation.top        # Back-to-top button
    
    # Important: Collapse all sections by default
    - navigation.collapse   # Collapse all sections by default
    
    # Table of contents behavior
    - toc.follow           # Table of contents follows scroll
    - toc.integrate        # Integrate section TOCs into navigation
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate

# Plugins
plugins:
  - search




# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: boeni-industries
      repo: aico
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree

# Enable collapsible navigation for all levels
# mkdocs-material: use navigation.tabs and navigation.sections options

theme:
  name: material
  logo: assets/images/logo.png
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.collapse
    - navigation.instant
    - navigation.tracking
    - toc.follow
  icon:
    repo: fontawesome/brands/github

# Custom CSS and JavaScript
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/nav-custom.css
extra_javascript:
  - assets/javascripts/extra.js
nav:
  - Welcome: welcome.md
  - Architecture:
      - Overview: architecture/architecture-overview.md
      - Configuration Management: architecture/configuration_management.md
      - Message Bus: architecture/message_bus.md
      - Technology Stack: architecture/tech_stack.md
  - Flows:
      - End-to-End Conversation: flows/conversation_e2e.md
  - Guides:
      - User:
          - Getting Started: guides/user/getting-started.md
      - Developer:
          - Getting Started: guides/developer/getting_started.md
          - Guidelines: guides/developer/guidelines.md
          - CLI Reference: guides/developer/cli_reference.md
          - Contributing: guides/developer/contributing.md
          - Schema Management: guides/developer/schema_management.md
          - Protobuf: guides/developer/protobuf.md
          - Namespaces: guides/developer/namespaces.md
          - Lessons Learned: guides/developer/lessons_learned.md
          - Versioning: guides/developer/versioning.md
          - Terminology/Glossary: guides/developer/terminology_glossary.md
          - Testing: guides/developer/testing.md
          - UUID Standards: guides/developer/uuid_standards.md
          - UV Cheatsheet: guides/developer/uv_cheatsheet.md
  - Subsystems:
      - Backend:
          - API Gateway: subsystems/backend/api_gateway.md
          - API Reference: subsystems/backend/api_reference.md
          - Plugin System: subsystems/backend/plugin_system.md
          - Log Consumer: subsystems/backend/log_consumer.md
          - Scheduling:
              - Overview: subsystems/backend/scheduling/scheduling.md
          - Conversation:
              - Overview: subsystems/backend/conversation/conversations.md
              - Thread Manager: subsystems/backend/conversation/conversations_thread_manager.md
      - CLI:
          - CLI: subsystems/cli/cli.md
      - Frontend:
          - Overview: subsystems/frontend/frontend_architecture_overview.md
          - API Integration: subsystems/frontend/api_integration.md
          - Component Library: subsystems/frontend/component_library.md
          - Design Principles: subsystems/frontend/design_principles.md
          - Navigation: subsystems/frontend/navigation.md
          - Networking: subsystems/frontend/networking.md
          - Performance Guidelines: subsystems/frontend/performance_guidelines.md
          - State Management: subsystems/frontend/state_management.md
          - Testing Strategy: subsystems/frontend/testing_strategy.md
          - User Flows: subsystems/frontend/user_flows.md
      - Modelservice:
          - Model Service: subsystems/modelservice/modelservice.md
      - Studio:
          - Admin UI: subsystems/studio/admin_ui.md
          - Master Admin UI: subsystems/studio/admin_ui_master.md
  - Concepts:
      - Data:
          - Data Layer: concepts/data/data_layer.md
          - Data Federation: concepts/data/data_federation.md
      - Embodiment: concepts/embodiment/embodiment.md
      - Emotion:
          - Architecture: concepts/emotion/emotion-sim-architecture.md
          - Messaging: concepts/emotion/emotion-sim-msg.md
          - Overview: concepts/emotion/emotion_sim.md
      - LLM:
          - Foundation Model: concepts/llm/foundation_model.md
          - Multimodality: concepts/llm/multimodality.md
      - Personality:
          - Architecture: concepts/personality/personality-sim-architecture.md
          - Messaging: concepts/personality/personality-sim-msg.md
          - Definition: concepts/personality/personality_definition.md
          - Overview: concepts/personality/personality_sim.md
      - Roaming:
          - P2P Mesh: concepts/roaming/p2p_mesh.md
          - Roaming: concepts/roaming/roaming.md
      - Social:
          - Social Relationship Modeling: concepts/social/social_relationship_modeling.md
  - Security:
      - Overview: security/security_overview.md
      - Data Security: security/data_security.md
      - Transport Security: security/transit_security.md
      - Access Control: security/access_control.md
      - Consent Manager: security/consent.md
      - Audit System: security/audit.md
  - Operations:
      - Update System: operations/update_system.md
  # - Administration:
  #     - Overview: admin/admin_overview.md
  #     - Admin UI: admin/admin_ui.md
  #     - Master Admin UI: admin/admin_ui_master.md
  #     - CLI: admin/cli.md
  # - Changelog: changelog.md  # Removed (404)
  - Glossary: guides/developer/terminology_glossary.md
  