site_name: AICO - AI Companion Project
site_description: Building an emotionally present, interactive AI companion
site_author: Michael Böni
site_url: https://boeni-industries.github.io/aico

# Configuration
use_directory_urls: true

# Repository
repo_name: boeni-industries/aico
repo_url: https://github.com/boeni-industries/aico
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Boeni Industries AG

# Build directory (default: site)
# Note: GitHub Actions will handle deployment to gh-pages branch
# No need to change site_dir for GitHub Pages deployment

# Configuration
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    # Navigation behavior
    - navigation.instant    # Instant loading navigation
    - navigation.tracking   # URL is automatically updated with anchor
    - navigation.sections   # Render sections as groups
    - navigation.indexes    # Section index pages
    - navigation.top        # Back-to-top button
    
    # Important: Collapse all sections by default
    - navigation.collapse   # Collapse all sections by default
    
    # Table of contents behavior
    - toc.follow           # Table of contents follows scroll
    - toc.integrate        # Integrate section TOCs into navigation
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate

# Plugins
plugins:
  - search




# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: boeni-industries
      repo: aico
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home:
      - Welcome: welcome.md
  - User Guide:
    - Overview: user-guide/getting_started.md
    - Installation: user-guide/installation.md
    - Quick Start: user-guide/quick_start.md
  - Architecture:
      - Overview: architecture/architecture_overview.md
  - Core Infrastructure:
    - Message Bus: architecture/message_bus.md
    - Plugin Manager: architecture/plugin_system.md
    - API Gateway: architecture/api_gateway.md
    - API Reference: architecture/api_reference.md
    - P2P Mesh Network: architecture/p2p_mesh.md
    - Device Roaming: architecture/roaming.md
    - Update System: architecture/update_system.md
    - Data Layer: architecture/data_layer.md
    - Data Federation: architecture/data_federation.md
    - Instrumentation: instrumentation/instrumentation.md
    - Logging: instrumentation/instrumentation_logging.md
    - Log Consumer: architecture/log_consumer.md
    - Telemetry: instrumentation/telemetry.md
  - Administration:
    - Overview: admin/admin_overview.md
    - Admin UI: admin/admin_ui.md
    - Master Admin UI: admin/admin_ui_master.md
    - CLI: admin/cli.md
  - Privacy & Security:
    - Overview: security/security_overview.md
    - Data Security: security/data_security.md
    - Transport Security: security/transit_security.md
    - Access Control: security/access_control.md
    - Consent Manager: security/consent.md
    - Audit System: security/audit.md  
  - Autonomous Agency:
    - Goal System: '#'
    - Planning System: '#'
    - Curiosity Engine: '#'
    - Initiative Manager: '#'
  - Personality & Emotion:
    - Personality Simulation: architecture/personality_sim.md
    - Emotion Simulation: architecture/emotion_sim.md
    - Emotion Recognition: '#'
    - Social Relationship Modeling: concepts/social/social_relationship_modeling.md
  - Self-Awareness:
    - State Monitoring: '#'
    - Meta-Cognition: '#'
  - Intelligence & Memory:
    - Chat Engine: '#'
    - Memory System: '#'
    - Learning System: '#'
  - User Interface:
    - Context Manager: '#'
    - Presentation Layer: '#'
  - Message Formats:
    - Core Integration: architecture/integration_msg.md
    - Emotion Simulation: architecture/emotion_sim_msg.md
    - Personality Simulation: architecture/personality_sim_msg.md
  - Technology Stack:
      - Overview: architecture/tech_stack.md
  - Concepts:
    - Emotion:
      - Emotion Simulation: concepts/emotion/emotion_sim.md
    - Personality:
      - Personality Simulation: concepts/personality/personality_sim.md
      - Personality Definition: concepts/personality/personality_definition.md
  - Frontend:
    - Architecture Overview: frontend/frontend_architecture_overview.md
    - UI/UX Design Principles: frontend/design_principles.md
    - State Management: frontend/state_management.md
    - Navigation: frontend/navigation.md
    - User Flows: frontend/user_flows.md
    - Networking: frontend/networking.md
    - API Integration: frontend/api_integration.md
    - Component Library: frontend/component_library.md
    - Performance: frontend/performance_guidelines.md
    - Testing: frontend/testing_strategy.md
  - Developer Guide:
    - Getting Started: developer-guide/getting_started.md
    - UV Commands Cheat Sheet: developer-guide/uv_cheatsheet.md
    - Guidelines: developer-guide/guidelines.md
    - Backend Patterns: developer-guide/backend_patterns.md
    - Contributing: developer-guide/contributing.md
    - Testing: developer-guide/testing.md
    - Protocol Buffers: developer-guide/protobuf.md
    - Versioning: developer-guide/versioning.md
    - Namespaces: developer-guide/namespaces.md
    - CLI Handbook: developer-guide/cli_handbook.md
    - Schema Management: developer-guide/schema_management.md
    - UUID Standards: developer-guide/uuid_standards.md
    - Lessons Learned: developer-guide/lessons_learned.md
  - Roadmap:
    - Foundation: roadmap/foundation.md
    - MVP: roadmap/mvp.md
    - Confidante: roadmap/confidante.md
    - Sidekick: roadmap/sidekick.md
    - Co-Adventurer: roadmap/co_adventurer.md
    - Embodied Presence: roadmap/embodied_presence.md
    - Community: roadmap/community.md
  # Additional sections will be added as features are implemented:
  # - Features:
  # - API Reference:
  # - Ethics & Privacy:
  # - Community:

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/boeni-industries/aico
    - icon: fontawesome/solid/globe
      link: https://boeni.industries
  
# Custom CSS and JavaScript
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/disable-logo.css
extra_javascript:
  - assets/javascripts/extra.js
# version:
    # provider: mike
