"""
Modelservice Metrics Instrumentation

Lightweight OpenTelemetry metrics for model inference tracking.
"""

import time
from typing import Optional, Dict, Any
from contextlib import contextmanager

from opentelemetry import metrics as otel_metrics

# Get OpenTelemetry meter
meter = otel_metrics.get_meter("aico.modelservice")

# Create histogram for inference duration
inference_duration = meter.create_histogram(
    name="aico.modelservice.inference.duration",
    description="Model inference duration in seconds",
    unit="s"
)

# Create counter for total inferences
inference_counter = meter.create_counter(
    name="aico.modelservice.inference.count",
    description="Total number of model inferences",
    unit="1"
)

# Create counter for tokens generated
tokens_counter = meter.create_counter(
    name="aico.modelservice.tokens.generated",
    description="Total tokens generated by models",
    unit="1"
)

# Create histogram for time to first token (TTFT) - LLM specific
ttft_histogram = meter.create_histogram(
    name="aico.modelservice.ttft",
    description="Time to first token for LLM streaming responses",
    unit="s"
)

# Create histogram for tokens per second (TPS) - LLM specific
tps_histogram = meter.create_histogram(
    name="aico.modelservice.tps",
    description="Tokens generated per second for LLM responses",
    unit="tokens/s"
)

# Create counter for entity extractions (NER specific)
entity_counter = meter.create_counter(
    name="aico.modelservice.entities.extracted",
    description="Total entities extracted by NER models",
    unit="1"
)

# Create histogram for confidence scores (sentiment/classification specific)
confidence_histogram = meter.create_histogram(
    name="aico.modelservice.confidence",
    description="Confidence scores for classification tasks",
    unit="1"
)


@contextmanager
def track_inference(
    model_name: str,
    task_type: str = "completion",
    **extra_attributes
):
    """
    Context manager for tracking model inference metrics.
    
    Usage:
        with track_inference("llama-3.2-3b", task_type="completion") as tracker:
            result = model.generate(prompt)
            tracker.set_tokens(len(result.tokens))
            tracker.set_success(True)
    
    Args:
        model_name: Name of the model being used
        task_type: Type of task (completion, embedding, sentiment, etc.)
        **extra_attributes: Additional attributes to record
    """
    start_time = time.perf_counter()
    
    # Tracker state
    tracker_state = {
        "tokens": 0,
        "success": True,
        "error": None,
        "ttft": None,  # Time to first token (for LLM streaming)
        "prompt_tokens": 0,  # Input tokens
        "entities_count": 0,  # For NER tasks
        "confidence": None,  # For classification tasks
        "sentiment": None,  # For sentiment analysis
        "entity_types": []  # For NER entity type tracking
    }
    
    class InferenceTracker:
        def set_tokens(self, count: int):
            """Set output tokens generated (for LLM tasks)"""
            tracker_state["tokens"] = count
        
        def set_prompt_tokens(self, count: int):
            """Set input prompt tokens (for LLM tasks)"""
            tracker_state["prompt_tokens"] = count
        
        def set_ttft(self, ttft_seconds: float):
            """Set time to first token (for LLM streaming)"""
            tracker_state["ttft"] = ttft_seconds
        
        def set_entities(self, count: int, entity_types: list = None):
            """Set entities extracted (for NER tasks)"""
            tracker_state["entities_count"] = count
            if entity_types:
                tracker_state["entity_types"] = entity_types
        
        def set_confidence(self, score: float):
            """Set confidence score (for classification tasks)"""
            tracker_state["confidence"] = score
        
        def set_sentiment(self, sentiment: str):
            """Set sentiment result (for sentiment analysis)"""
            tracker_state["sentiment"] = sentiment
        
        def set_success(self, success: bool):
            tracker_state["success"] = success
        
        def set_error(self, error: str):
            tracker_state["error"] = error
            tracker_state["success"] = False
    
    tracker = InferenceTracker()
    
    try:
        yield tracker
    finally:
        # Calculate duration
        duration = time.perf_counter() - start_time
        duration_ms = duration * 1000  # Convert to milliseconds
        
        # Build attributes
        attributes = {
            "model.name": model_name,
            "task.type": task_type,
            "success": tracker_state["success"],
            **extra_attributes
        }
        
        # Record OpenTelemetry metrics
        inference_duration.record(duration, attributes)
        inference_counter.add(1, attributes)
        
        # LLM-specific metrics
        if tracker_state["tokens"] > 0:
            attributes["tokens.generated"] = tracker_state["tokens"]
            tokens_counter.add(tracker_state["tokens"], attributes)
            
            # Calculate and record TPS (tokens per second)
            if duration > 0:
                tps = tracker_state["tokens"] / duration
                tps_histogram.record(tps, attributes)
        
        if tracker_state["prompt_tokens"] > 0:
            attributes["prompt.tokens"] = tracker_state["prompt_tokens"]
        
        if tracker_state["ttft"] is not None:
            attributes["ttft"] = tracker_state["ttft"]  # Add to attributes for InfluxDB export
            ttft_histogram.record(tracker_state["ttft"], attributes)
        
        # NER-specific metrics
        if tracker_state["entities_count"] > 0:
            attributes["entities.count"] = tracker_state["entities_count"]
            entity_counter.add(tracker_state["entities_count"], attributes)
            
            if tracker_state["entity_types"]:
                # Store entity types as comma-separated string for aggregation
                attributes["entity.types"] = ",".join(tracker_state["entity_types"])
        
        # Classification-specific metrics
        if tracker_state["confidence"] is not None:
            attributes["confidence.score"] = tracker_state["confidence"]
            confidence_histogram.record(tracker_state["confidence"], attributes)
        
        if tracker_state["sentiment"] is not None:
            attributes["sentiment.result"] = tracker_state["sentiment"]


def record_inference(
    model_name: str,
    duration: float,
    tokens_generated: int = 0,
    success: bool = True,
    error: str = None,
    attributes: dict = None
):
    """
    Record inference metrics directly (without context manager).
    
    Args:
        model_name: Name of the model
        duration: Inference duration in seconds
        tokens_generated: Number of tokens generated (optional)
        tokens: Number of tokens generated (optional)
        success: Whether inference succeeded
        task_type: Type of task
        **extra_attributes: Additional attributes
    """
    attributes = {
        "model.name": model_name,
        "task.type": task_type,
        "success": success,
        **extra_attributes
    }
    
    # Record OpenTelemetry metrics
    inference_duration.record(duration_seconds, attributes)
    inference_counter.add(1, attributes)
    
    if tokens is not None and tokens > 0:
        attributes["tokens.generated"] = tokens
        tokens_counter.add(tokens, attributes)
