# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/logging.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'core/logging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ore/logging.proto\x12\taico.core\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x03\n\x08LogEntry\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\"\n\x05level\x18\x02 \x01(\x0e\x32\x13.aico.core.LogLevel\x12\x11\n\tsubsystem\x18\x03 \x01(\t\x12\x0e\n\x06module\x18\x04 \x01(\t\x12\x10\n\x08\x66unction\x18\x05 \x01(\t\x12\x0f\n\x07message\x18\x06 \x01(\t\x12\r\n\x05topic\x18\x07 \x01(\t\x12\x33\n\x08metadata\x18\x08 \x03(\x0b\x32!.aico.core.LogEntry.MetadataEntry\x12\x11\n\tfile_path\x18\t \x01(\t\x12\x13\n\x0bline_number\x18\n \x01(\x05\x12\x0f\n\x07user_id\x18\x0b \x01(\t\x12\x12\n\nsession_id\x18\x0c \x01(\t\x12\x10\n\x08trace_id\x18\r \x01(\t\x12-\n\x05\x65xtra\x18\x0e \x03(\x0b\x32\x1e.aico.core.LogEntry.ExtraEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xee\x01\n\x0fLogQueryRequest\x12#\n\x06levels\x18\x01 \x03(\x0e\x32\x13.aico.core.LogLevel\x12\x12\n\nsubsystems\x18\x02 \x03(\t\x12\x0f\n\x07modules\x18\x03 \x03(\t\x12.\n\nstart_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05limit\x18\x06 \x01(\x05\x12\x0e\n\x06offset\x18\x07 \x01(\x05\x12\x14\n\x0csearch_query\x18\x08 \x01(\t\"_\n\x10LogQueryResponse\x12$\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x13.aico.core.LogEntry\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\x12\x10\n\x08has_more\x18\x03 \x01(\x08*R\n\x08LogLevel\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x44\x45\x42UG\x10\n\x12\x08\n\x04INFO\x10\x14\x12\x0b\n\x07WARNING\x10\x1e\x12\t\n\x05\x45RROR\x10(\x12\x0c\n\x08\x43RITICAL\x10\x32\x42Q\n industries.boeni.aico.proto.coreP\x01Z+github.com/boeni-industries/aico/proto/coreb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n industries.boeni.aico.proto.coreP\001Z+github.com/boeni-industries/aico/proto/core'
  _globals['_LOGENTRY_METADATAENTRY']._loaded_options = None
  _globals['_LOGENTRY_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_LOGENTRY_EXTRAENTRY']._loaded_options = None
  _globals['_LOGENTRY_EXTRAENTRY']._serialized_options = b'8\001'
  _globals['_LOGLEVEL']._serialized_start=875
  _globals['_LOGLEVEL']._serialized_end=957
  _globals['_LOGENTRY']._serialized_start=67
  _globals['_LOGENTRY']._serialized_end=535
  _globals['_LOGENTRY_METADATAENTRY']._serialized_start=442
  _globals['_LOGENTRY_METADATAENTRY']._serialized_end=489
  _globals['_LOGENTRY_EXTRAENTRY']._serialized_start=491
  _globals['_LOGENTRY_EXTRAENTRY']._serialized_end=535
  _globals['_LOGQUERYREQUEST']._serialized_start=538
  _globals['_LOGQUERYREQUEST']._serialized_end=776
  _globals['_LOGQUERYRESPONSE']._serialized_start=778
  _globals['_LOGQUERYRESPONSE']._serialized_end=873
# @@protoc_insertion_point(module_scope)
