"""
JSON Sanitizer for LLM-generated JSON output.

This module provides robust JSON parsing and repair capabilities specifically
designed for handling malformed JSON commonly generated by Large Language Models.

Uses the industry-standard json-repair library combined with custom preprocessing
for LLM-specific issues.
"""

import json
import re
from typing import Any, Dict, List, Optional, Union
from enum import Enum

from aico.core.logging import get_logger

try:
    from json_repair import repair_json
    JSON_REPAIR_AVAILABLE = True
except ImportError:
    JSON_REPAIR_AVAILABLE = False

logger = get_logger("aico.core.json_sanitizer")


class RepairStrategy(Enum):
    """Strategies for JSON repair attempts."""
    DIRECT = "direct"  # Try parsing directly
    EXTRACT = "extract"  # Extract JSON from surrounding text
    PREPROCESS = "preprocess"  # Apply LLM-specific preprocessing
    REPAIR = "repair"  # Use json-repair library
    AGGRESSIVE = "aggressive"  # Aggressive fixes (may alter content)


class LLMJsonSanitizer:
    """
    Robust JSON sanitizer for LLM-generated output.
    
    Handles common LLM JSON generation issues:
    - Extra spaces before quotes: ` "key"` → `"key"`
    - Missing quotes on keys/values
    - Trailing commas
    - Incomplete structures
    - Mixed quotes (single/double)
    - Unescaped characters
    - Extra text before/after JSON
    
    Example:
        >>> sanitizer = LLMJsonSanitizer()
        >>> result = sanitizer.sanitize(llm_output)
        >>> if result.success:
        >>>     data = result.data
        >>>     print(f"Fixed using: {result.strategy}")
    """
    
    def __init__(self, strict: bool = False, log_repairs: bool = True):
        """
        Initialize JSON sanitizer.
        
        Args:
            strict: If True, only allow valid JSON (no aggressive repairs)
            log_repairs: If True, log all repair attempts and results
        """
        self.strict = strict
        self.log_repairs = log_repairs
        
        if not JSON_REPAIR_AVAILABLE:
            logger.debug(
                "[JSON_SANITIZER] json-repair library not available. "
                "Install with: pip install json-repair"
            )
    
    def sanitize(
        self,
        json_string: str,
        expected_type: Optional[type] = None,
        return_objects: bool = True
    ) -> 'SanitizeResult':
        """
        Sanitize and parse JSON string from LLM output.
        
        Args:
            json_string: Raw string from LLM (may contain invalid JSON)
            expected_type: Expected type (dict, list, etc.) for validation
            return_objects: If True, return parsed objects; if False, return string
            
        Returns:
            SanitizeResult with success status, data, and metadata
        """
        if not json_string or not json_string.strip():
            return SanitizeResult(
                success=False,
                error="Empty input string",
                original=json_string
            )
        
        original = json_string
        
        # Strategy 1: Try direct parsing (fastest)
        result = self._try_direct_parse(json_string, expected_type, return_objects)
        if result.success:
            if self.log_repairs:
                logger.debug("[JSON_SANITIZER] Direct parse successful")
            return result
        
        # Strategy 2: Extract JSON from surrounding text
        result = self._try_extract_json(json_string, expected_type, return_objects)
        if result.success:
            if self.log_repairs:
                logger.info(f"[JSON_SANITIZER] Extracted JSON from text (strategy: {result.strategy})")
            return result
        
        # Strategy 3: Preprocess for common LLM issues
        result = self._try_preprocess(json_string, expected_type, return_objects)
        if result.success:
            if self.log_repairs:
                logger.info(f"[JSON_SANITIZER] Fixed with preprocessing (strategy: {result.strategy})")
            return result
        
        # Strategy 4: Use json-repair library
        if JSON_REPAIR_AVAILABLE:
            result = self._try_repair_library(json_string, expected_type, return_objects)
            if result.success:
                if self.log_repairs:
                    logger.info(f"[JSON_SANITIZER] Fixed with json-repair (strategy: {result.strategy})")
                return result
        
        # Strategy 5: Aggressive fixes (if not strict mode)
        if not self.strict:
            result = self._try_aggressive_fixes(json_string, expected_type, return_objects)
            if result.success:
                if self.log_repairs:
                    logger.warning(
                        f"[JSON_SANITIZER] Fixed with aggressive repairs (strategy: {result.strategy}). "
                        "Content may have been altered."
                    )
                return result
        
        # All strategies failed
        logger.error(f"[JSON_SANITIZER] All repair strategies failed for input: {original[:200]}...")
        return SanitizeResult(
            success=False,
            error="All repair strategies failed",
            original=original,
            strategy=RepairStrategy.AGGRESSIVE
        )
    
    def _try_direct_parse(
        self,
        json_string: str,
        expected_type: Optional[type],
        return_objects: bool
    ) -> 'SanitizeResult':
        """Try parsing JSON directly without any fixes."""
        try:
            data = json.loads(json_string)
            if expected_type and not isinstance(data, expected_type):
                return SanitizeResult(
                    success=False,
                    error=f"Expected {expected_type}, got {type(data)}",
                    original=json_string
                )
            return SanitizeResult(
                success=True,
                data=data if return_objects else json_string,
                original=json_string,
                strategy=RepairStrategy.DIRECT
            )
        except json.JSONDecodeError as e:
            return SanitizeResult(
                success=False,
                error=str(e),
                original=json_string
            )
    
    def _try_extract_json(
        self,
        text: str,
        expected_type: Optional[type],
        return_objects: bool
    ) -> 'SanitizeResult':
        """Extract JSON from surrounding text."""
        # Find JSON array or object boundaries
        start_idx = -1
        end_idx = -1
        
        # Try to find array
        array_start = text.find('[')
        array_end = text.rfind(']')
        
        # Try to find object
        obj_start = text.find('{')
        obj_end = text.rfind('}')
        
        # Use whichever appears first
        if array_start != -1 and (obj_start == -1 or array_start < obj_start):
            start_idx = array_start
            end_idx = array_end + 1 if array_end != -1 else -1
        elif obj_start != -1:
            start_idx = obj_start
            end_idx = obj_end + 1 if obj_end != -1 else -1
        
        if start_idx == -1 or end_idx == -1 or end_idx <= start_idx:
            return SanitizeResult(
                success=False,
                error="No JSON structure found",
                original=text
            )
        
        json_str = text[start_idx:end_idx]
        return self._try_direct_parse(json_str, expected_type, return_objects)._replace(
            strategy=RepairStrategy.EXTRACT
        )
    
    def _try_preprocess(
        self,
        json_string: str,
        expected_type: Optional[type],
        return_objects: bool
    ) -> 'SanitizeResult':
        """Apply LLM-specific preprocessing fixes."""
        fixed = json_string
        
        # Fix 1: Remove extra spaces before quotes in keys
        # Pattern: `{ "key"` or `, "key"` with extra space before quote
        fixed = re.sub(r'([{\,])\s+"\s+"', r'\1 "', fixed)
        
        # Fix 2: Remove newlines within string values
        fixed = re.sub(r'"\s*\n\s*"', '" "', fixed)
        
        # Fix 3: Fix unescaped quotes within strings (common LLM error)
        # This is tricky - only fix obvious cases
        fixed = re.sub(r'(?<!\\)"(?=\w)', r'\\"', fixed)
        
        # Fix 4: Remove trailing commas before closing brackets
        fixed = re.sub(r',\s*([}\]])', r'\1', fixed)
        
        # Fix 5: Add missing commas between array/object elements
        fixed = re.sub(r'([}\]])\s*\n\s*([{\[])', r'\1,\2', fixed)
        
        result = self._try_direct_parse(fixed, expected_type, return_objects)
        if result.success:
            return result._replace(strategy=RepairStrategy.PREPROCESS)
        return result
    
    def _try_repair_library(
        self,
        json_string: str,
        expected_type: Optional[type],
        return_objects: bool
    ) -> 'SanitizeResult':
        """Use json-repair library to fix JSON."""
        try:
            if return_objects:
                # Use repair_json with return_objects=True
                data = repair_json(json_string, return_objects=True)
            else:
                # Return repaired string
                data = repair_json(json_string, return_objects=False)
            
            if expected_type and return_objects and not isinstance(data, expected_type):
                return SanitizeResult(
                    success=False,
                    error=f"Expected {expected_type}, got {type(data)}",
                    original=json_string
                )
            
            return SanitizeResult(
                success=True,
                data=data,
                original=json_string,
                strategy=RepairStrategy.REPAIR
            )
        except Exception as e:
            return SanitizeResult(
                success=False,
                error=f"json-repair failed: {e}",
                original=json_string
            )
    
    def _try_aggressive_fixes(
        self,
        json_string: str,
        expected_type: Optional[type],
        return_objects: bool
    ) -> 'SanitizeResult':
        """Apply aggressive fixes that may alter content."""
        fixed = json_string
        
        # Aggressive Fix 1: Replace single quotes with double quotes
        fixed = fixed.replace("'", '"')
        
        # Aggressive Fix 2: Remove all non-JSON characters before first bracket
        fixed = re.sub(r'^[^[{]*', '', fixed)
        
        # Aggressive Fix 3: Remove all non-JSON characters after last bracket
        fixed = re.sub(r'[^}\]]*$', '', fixed)
        
        # Aggressive Fix 4: Fix common word insertions
        fixed = re.sub(r'\b(json|JSON|here|Here|output|Output):\s*', '', fixed)
        
        result = self._try_direct_parse(fixed, expected_type, return_objects)
        if result.success:
            return result._replace(strategy=RepairStrategy.AGGRESSIVE)
        return result


class SanitizeResult:
    """Result of JSON sanitization attempt."""
    
    def __init__(
        self,
        success: bool,
        data: Any = None,
        error: Optional[str] = None,
        original: Optional[str] = None,
        strategy: Optional[RepairStrategy] = None
    ):
        self.success = success
        self.data = data
        self.error = error
        self.original = original
        self.strategy = strategy
    
    def _replace(self, **kwargs):
        """Create a new result with updated fields."""
        return SanitizeResult(
            success=kwargs.get('success', self.success),
            data=kwargs.get('data', self.data),
            error=kwargs.get('error', self.error),
            original=kwargs.get('original', self.original),
            strategy=kwargs.get('strategy', self.strategy)
        )
    
    def __repr__(self):
        return (
            f"SanitizeResult(success={self.success}, "
            f"strategy={self.strategy.value if self.strategy else None}, "
            f"error={self.error})"
        )


# Convenience functions for common use cases

def sanitize_llm_json(
    json_string: str,
    expected_type: Optional[type] = None,
    strict: bool = False
) -> SanitizeResult:
    """
    Convenience function to sanitize LLM-generated JSON.
    
    Args:
        json_string: Raw JSON string from LLM
        expected_type: Expected type (dict, list, etc.)
        strict: If True, only allow valid JSON (no aggressive repairs)
        
    Returns:
        SanitizeResult with parsed data or error
        
    Example:
        >>> result = sanitize_llm_json(llm_output, expected_type=list)
        >>> if result.success:
        >>>     steps = result.data
    """
    sanitizer = LLMJsonSanitizer(strict=strict)
    return sanitizer.sanitize(json_string, expected_type=expected_type)


def parse_llm_json(json_string: str, default: Any = None) -> Any:
    """
    Parse LLM-generated JSON, returning default on failure.
    
    Args:
        json_string: Raw JSON string from LLM
        default: Value to return if parsing fails
        
    Returns:
        Parsed data or default value
        
    Example:
        >>> steps = parse_llm_json(llm_output, default=[])
    """
    result = sanitize_llm_json(json_string)
    return result.data if result.success else default
