server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 24h

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    block:
      version: vParquet4

metrics_generator:
  storage:
    path: /var/tempo/generator

query_frontend:
  search:
    query_backend_after: 0s
    query_ingesters_until: 1h

querier:
  frontend_worker:
    frontend_address: 127.0.0.1:9095

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]
