// Mocks generated by Mockito 5.5.0 from annotations
// in settings_bloc_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart';
import 'package:aico_ui/features/settings/repositories/settings_repository.dart';

class MockSettingsRepository extends Mock implements SettingsRepository {}
